/// Flutter icons CustomSocial
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomSocial
///      fonts:
///       - asset: fonts/CustomSocial.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class CustomSocial {
  CustomSocial._();

  static const _kFontFam = 'CustomSocial';
  static const String? _kFontPkg = null;

  static const IconData github_circled = IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_circled = IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_circled = IconData(0xf319, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
